### ISSUE TITLE
Version numbers of the linux zip builds seem to be broken.

### ISSUE THREAD

**Issue by EraYaN** [noborus/pgsp#6]
Linux
```
host:~$ pgsp --version
pgsp version dev rev:HEAD
``` 

vs 
Windows:
```
C:\>pgsp --version
pgsp version 0.0.5 rev:748a12b
```

That can probably be fixing the ldflags in the .goreleaser.yml to be the same across linux and other builds

**Comment by noborus** [comment]
Thank you for reporting the issue.
As you said, I made a mistake.
